### ISSUE TITLE
King of Night's Frost Embrace does nothing

### ISSUE THREAD

**Issue by Arkandos** [Freeman322/Comics-Heroes-Wars#10]
Frost Embrace (E) does nothing. It has no chance to convert anything, nor does it deal extra damage.

**Comment by Freeman322** [comment]
It cant be true. I checked it. Just attack creeps and ull see.

**Comment by Arkandos** [comment]
It did not happen until I maxed it. And the tooltip should be changed to reflect that it only works on junglecreeps

**Comment by Arkandos** [comment]
Also, his ult does not show the range, and upgrading it does nothing?
Update: Now I really don't know what this hero is useful for. His ult does not even give the hero copies their items? Just illusions that deal next to no damage?
