### ISSUE TITLE
[Balance] Balance discussion list

### ISSUE THREAD

**Issue by Arkandos** [Freeman322/Comics-Heroes-Wars#5]
- [ ] "For every hero killed, Hela receives bonus damage and spell power. The bonus is lost after death." 
This seems unnecessarily harsh, to lose the bonuses when you die. No other character loses their stacks when they die.
- [ ] Make King of Night's E conversion an aura, or give converted creeps severe buffs. As it stands, the ability is just good for extra PvE dmg.
- [ ] Dormammu's E being Pure AND doing damage to structures. I don't even...
- [ ] Byonders infinite stat buff. Why can he gain infinite damage and health, but Hela cannot?

**Comment by Gleor** [comment]
It was made because of balance. Other way she will be able to have infinite damage (in potential)

**Comment by Arkandos** [comment]
Then perhaps make her lose the spellpower on death, but keep the damage? I mean all intelligence heroes steal infinite int.

**Comment by Freeman322** [comment]
Not infinite. Same as Silencer. Only base int.

**Comment by Arkandos** [comment]
Drax has infinite Str, meaning infinite damage and infinite health.
Why could not Hela have it?

**Comment by Freeman322** [comment]
Cause modifier steals only base Int.

**Comment by Arkandos** [comment]
Butcher has infinite stats, Byonder has infinite stats without needing to kill someone. The list just goes on. So I don't think the argument works here.
