### ISSUE TITLE
Item bugs

### ISSUE THREAD

**Issue by Arkandos** [Freeman322/Comics-Heroes-Wars#9]
- [ ] Aeon Disk / Dawnbreaker does not make you immune to all damage. For example Blade of Darkness and Deathscythe pierces it
- [ ] Infinity Dagon Scepter does not function like an aghanims for granting extra abilities, for example Celebrimbor

**Comment by Freeman322** [comment]
Are you sure? Cause item has all state modifiers...

```function modifier_item_dawnbreaker_active:CheckState ()
    local state = {
        [MODIFIER_STATE_INVULNERABLE] = true,
        [MODIFIER_STATE_SILENCED] = true,
        [MODIFIER_STATE_ATTACK_IMMUNE] = true,
        [MODIFIER_STATE_MUTED] = true,
        [MODIFIER_STATE_DISARMED] = true,
        [MODIFIER_STATE_NO_UNIT_COLLISION] = true,
        [MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY] = true
    }

    return state
end

**Comment by Arkandos** [comment]
I have died several times using the items whilst only being attacked. Should be pretty straightforward to check.
Update: It does without a doubt pierce Aeon disk.
